# Use a minimal base image
FROM ubuntu:latest

# Install iptables
RUN apt-get update && \
    apt-get install -y iptables iproute2 tcpdump gcc libpcap-dev make sysstat && \
    apt-get clean

CMD ["sleep", "infinity"]
