# Write a suricata docker file..
# Install suricata packet inspection tool and configure the image to run infinitely

FROM ubuntu:latest
RUN apt-get update

RUN apt-get install software-properties-common iproute2 iptables nano -y

RUN add-apt-repository ppa:oisf/suricata-stable

RUN apt-get install suricata -y

RUN apt-get update && \
    apt-get install -y linux-tools-common linux-tools-generic linux-tools-$(uname -r) && \
    apt-get clean


CMD ["sleep", "infinity"]