FROM ubuntu:latest

# Install all the libraries
RUN apt-get update && apt-get install -y \
    iperf3 \
    netperf \
    nuttcp \
    redis-tools \
    sysbench \
    mysql-client \
    fio \
    traceroute \
    iproute2 \
    && apt-get clean

CMD ["sleep", "infinity"]